# Generated by Django 5.2.8 on 2025-11-28 19:31

import data_sel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=data_sel.models.timestamped_filename),
        ),
    ]
